repositories:
  - name: external-secrets
    url: https://charts.external-secrets.io
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: external-secrets
    namespace: external-secrets
    chart: external-secrets/external-secrets
    values:
      - charts/external-secrets/values.yaml
  - chart: ingress-nginx/ingress-nginx
    version: 4.1.0
    name: nginx-ingress
